version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Zurich"
    commit-message:
      prefix: ":seedling:"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
      timezone: "Europe/Zurich"
    commit-message:
      prefix: ":robot:"
    labels:
      - "dependencies"
      - "go"
    open-pull-requests-limit: 10
