defaultBaseImage: cgr.dev/chainguard/static:latest@sha256:f51c2493951313c3ad4069080b2814ffb6ed6fe3909dabeb84a9482f42d5600b
defaultPlatforms:
# possible values: all, linux/s390x, linux/arm64, linux/arm/v7, linux/ppc64le, linux/amd64
- linux/arm64
- linux/arm/v7
- linux/amd64
builds:
- id: pbs-exporter
  main: ./
  flags:
  - -tags
  - netgo
  ldflags:
  - '{{ if index .Env "LD_FLAGS" }}{{ .Env.LD_FLAGS }}{{ end }}'
