name: "Gosec Security Scan"

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - id: checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
    - name: Run Gosec Security Scanner
      env:
        GOTOOLCHAIN: "go1.26.5"
      uses: securego/gosec@deb54465fea23d19a77f037e11e6589021f8501d # v2.29.0
      with:
        args: ./...
