name: "Gosec Security Scan"

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  analyze:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
    - id: checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - name: Run Gosec Security Scanner
      env:
        GOTOOLCHAIN: "go1.26.4"
      uses: securego/gosec@4a3bd8af174872c778439083ded7adbf3747e770 # v2.26.1
      with:
        args: ./...
