name: OSV-Scanner Scan

on:
  schedule:
    - cron: '30 13 * * 1'
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  analyze:
    permissions:
      # Require writing security events to upload SARIF file to security tab
      security-events: write
      contents: read
      actions: read
    uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@8deb546fdb875b9996d27d4950be7312dac076a1" #v2.5.0
